# Generated by Django 6.0.3 on 2026-04-06 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0002_user_direccion_user_foto_user_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_compra_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_compra', models.DateField()),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('formato_importacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.oficina')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='catalog.parte')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('nivel', models.CharField(choices=[('INFO', 'Info'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.oficina')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.parte')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_disponible', models.PositiveIntegerField(default=0)),
                ('cant_en_transito', models.PositiveIntegerField(default=0)),
                ('cant_danada_por_recibir', models.PositiveIntegerField(default=0)),
                ('foto_factura', models.ImageField(blank=True, null=True, upload_to='facturas/%Y/%m/')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.oficina')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.parte')),
            ],
            options={
                'unique_together': {('parte', 'oficina')},
            },
        ),
    ]
