# Generated by Django 6.0.3 on 2026-04-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='foto_factura',
            field=models.ImageField(blank=True, null=True, upload_to='facturas/%Y/%m/'),
        ),
    ]
