# Generated by Django 6.0.3 on 2026-04-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimiento',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.oficina'),
        ),
        migrations.AddField(
            model_name='abastecimiento',
            name='parte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='catalog.parte'),
        ),
        migrations.AddField(
            model_name='alertainventario',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.oficina'),
        ),
        migrations.AddField(
            model_name='alertainventario',
            name='parte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.parte'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.oficina'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='parte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.parte'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('parte', 'oficina')},
        ),
    ]
