# Generated by Django 6.0.3 on 2026-04-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventario_foto_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Serial'),
        ),
    ]
