# Generated by Django 6.0.3 on 2026-04-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventario_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cant_disponible',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
