# Generated by Django 6.0.3 on 2026-04-08 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventario_cant_disponible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoKardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Abastecimiento/Compra)'), ('SALIDA', 'Salida (Despacho a Técnico)'), ('DEVOLUCION', 'Devolución (Retorno al Almacén)'), ('AJUSTE', 'Ajuste (Auditoría/Pérdida)')], max_length=15)),
                ('cantidad', models.PositiveIntegerField()),
                ('referencia', models.CharField(help_text='Ej: Factura #001 o Orden de Servicio #50', max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('saldo_anterior', models.IntegerField(editable=False)),
                ('saldo_nuevo', models.IntegerField(editable=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventory.inventario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Kardex',
                'verbose_name_plural': 'Kardex: Historial de Movimientos',
            },
        ),
    ]
