# Generated by Django 6.0.3 on 2026-04-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_movimientokardex'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientokardex',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial del Ítem'),
        ),
    ]
