# Generated by Django 6.0.3 on 2026-04-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0006_movimientokardex_serial'),
        ('users', '0002_user_direccion_user_foto_user_telefono_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('parte', 'oficina', 'serial')},
        ),
    ]
