# Generated by Django 6.0.3 on 2026-04-19 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0007_alter_inventario_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientokardex',
            options={},
        ),
        migrations.RemoveField(
            model_name='abastecimiento',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='abastecimiento',
            name='formato_importacion',
        ),
        migrations.RemoveField(
            model_name='movimientokardex',
            name='serial',
        ),
        migrations.AddField(
            model_name='abastecimiento',
            name='usuario_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abastecimiento',
            name='parte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.parte'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cant_disponible',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimientokardex',
            name='referencia',
            field=models.CharField(max_length=100),
        ),
    ]
