# Generated by Django 6.0.3 on 2026-04-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_movimientokardex_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertaInventario',
        ),
    ]
