# Generated by Django 6.0.3 on 2026-04-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_delete_alertainventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientokardex',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimientokardex',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='movimientokardex',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimientokardex',
            name='referencia',
            field=models.CharField(help_text='Ej: OC-2024, Guía #45', max_length=100),
        ),
        migrations.AlterField(
            model_name='movimientokardex',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Compra / Abastecimiento'), ('SALIDA', 'Despacho a Técnico'), ('DEVOLUCION', 'Retorno de Parte'), ('AJUSTE', 'Ajuste de Inventario')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Abastecimiento',
        ),
    ]
