# Generated by Django 6.0.3 on 2026-04-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_movimientokardex_numero_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientokardex',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
