# Generated by Django 6.0.3 on 2026-04-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_movimientokardex_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cant_disponible',
            field=models.IntegerField(default=0, verbose_name='Cantidad en stock'),
        ),
    ]
