# Generated by Django 6.0.3 on 2026-04-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_parte_tiene_serial'),
        ('inventory', '0012_alter_inventario_cant_disponible'),
        ('users', '0002_user_direccion_user_foto_user_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientokardex',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='movimientokardex',
            name='saldo_anterior',
        ),
        migrations.RemoveField(
            model_name='movimientokardex',
            name='saldo_nuevo',
        ),
        migrations.AddField(
            model_name='movimientokardex',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.oficina'),
        ),
        migrations.AddField(
            model_name='movimientokardex',
            name='parte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.parte'),
        ),
        migrations.AlterField(
            model_name='movimientokardex',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='movimientokardex',
            name='observaciones',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientokardex',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='movimientokardex',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10),
        ),
    ]
