# Generated by Django 6.0.3 on 2026-04-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_movimientokardex_inventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serial'),
        ),
    ]
