# Generated by Django 6.0.3 on 2026-04-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_inventario_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientokardex',
            name='estado_parte',
            field=models.CharField(choices=[('OPERATIVO', 'Operativo / Nuevo'), ('DAÑADO', 'Dañado / Para Reparar'), ('DESECHO', 'Desecho / Scrap')], default='OPERATIVO', max_length=20),
        ),
    ]
