# Generated by Django 6.0.3 on 2026-04-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Línea de Negocio',
                'verbose_name_plural': 'Líneas de Negocio',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipos/')),
                ('linea_negocio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='catalog.lineanegocio')),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='partes/')),
                ('equipos_compatibles', models.ManyToManyField(blank=True, related_name='partes', to='catalog.equipo')),
            ],
        ),
    ]
