# Generated by Django 6.0.3 on 2026-04-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='tiene_serial',
            field=models.BooleanField(default=False, help_text='Marque si la pieza se controla por serial único (Activo)', verbose_name='¿Es serializada?'),
        ),
    ]
