# Generated by Django 6.0.3 on 2026-04-03 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Línea de Negocio',
                'verbose_name_plural': 'Líneas de Negocio',
            },
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='tipo_tecnologia',
        ),
        migrations.AddField(
            model_name='parte',
            name='equipos_compatibles',
            field=models.ManyToManyField(blank=True, related_name='partes', to='catalog.equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='linea_negocio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='catalog.lineanegocio'),
            preserve_default=False,
        ),
    ]
