# Generated by Django 6.0.3 on 2026-04-03 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_lineanegocio_remove_equipo_tipo_tecnologia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='linea_negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='catalog.lineanegocio'),
        ),
    ]
