# Generated by Django 6.0.3 on 2026-04-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_equipo_linea_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/'),
        ),
        migrations.AddField(
            model_name='parte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='partes/'),
        ),
    ]
