# Generated by Django 6.0.3 on 2026-04-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DESPACHO', 'Despacho al técnico'), ('RETORNO', 'Retorno al almacén')], max_length=20)),
                ('guia_courier', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=50)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_crm', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('DESPACHADA', 'Despachada'), ('RESUELTO', 'Resuelto (CRM OK)'), ('CERRADA', 'Cerrada (Logística OK)')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.parte')),
            ],
        ),
    ]
