# Generated by Django 6.0.3 on 2026-04-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_envio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='fecha_envio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
