# Generated by Django 6.0.3 on 2026-04-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_solicitud_observaciones_solicitud_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='tipo',
            field=models.CharField(choices=[('DESPACHADA', 'Despacho al técnico'), ('RETORNO', 'Retorno al almacén')], max_length=20),
        ),
    ]
