# Generated by Django 6.0.3 on 2026-04-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_envio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='serial_devuelto',
            field=models.CharField(blank=True, help_text='Serial de la pieza dañada', max_length=100, null=True),
        ),
    ]
