# Generated by Django 6.0.3 on 2026-04-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_envio_serial_devuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitud',
            name='serial',
            field=models.CharField(blank=True, help_text='Solo para partes serializadas', max_length=100, null=True),
        ),
    ]
