# Generated by Django 6.0.3 on 2026-04-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_parte_tiene_serial'),
        ('operations', '0005_detallesolicitud_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetornoParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_retirado', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.parte')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.solicitud')),
            ],
        ),
    ]
