# Generated by Django 6.0.3 on 2026-04-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_retornoparte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='serial_devuelto',
        ),
    ]
