# Generated by Django 6.0.3 on 2026-04-24 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_remove_envio_serial_devuelto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retornoparte',
            options={'verbose_name': 'Retorno de Parte', 'verbose_name_plural': 'Retornos de Partes'},
        ),
        migrations.RemoveField(
            model_name='retornoparte',
            name='serial_retirado',
        ),
        migrations.AddField(
            model_name='retornoparte',
            name='almacenista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retornos_verificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retornoparte',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retornoparte',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='retornoparte',
            name='serial_extraido',
            field=models.CharField(default=1, max_length=100, verbose_name='Serial Retirado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retornoparte',
            name='tecnico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='retornos_realizados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retornoparte',
            name='estado',
            field=models.CharField(choices=[('TRANSITO', 'En Tránsito (Técnico)'), ('RECIBIDO', 'Recibido en Almacén'), ('DISCREPANCIA', 'Error en Serial')], default='TRANSITO', max_length=20),
        ),
        migrations.AlterField(
            model_name='retornoparte',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='retornoparte',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retornos', to='operations.solicitud'),
        ),
    ]
