# Generated by Django 6.0.3 on 2026-04-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_alter_retornoparte_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='tipo',
            field=models.CharField(choices=[('DESPACHADA', 'Despacho al técnico')], max_length=20),
        ),
    ]
